#
# Executes commands at login post-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Print a random, hopefully interesting, adage, and the hostname.
if (( $+commands[fortune] )); then
  if [[ -t 0 || -t 1 ]]; then
    print
    if (( $+commands[figlet] )); then
      figlet -ct $(hostname) 
      print
    fi
    fortune -as
    print
  fi
fi

# Stop annoying Ctrl-S behaviour (turn flow control off)

if (( $+commands[stty] )); then
  stty -ixon
fi
